### ISSUE TITLE
Enable support for StreamingResponse

### ISSUE THREAD

**Issue by bbezuk** [Tinche/uapi#42]
When using aiohttp response

`from aiohttp.web import StreamResponse
`
as a response from handler it currently throws an error. Using regular response works as a workaround but it would be nice if I could use Streamresponse.

Also adding this as a supported feature for openapi generation would be useful. I assume all underlying frameworks have some kind of Streaming respose.

**Comment by Tinche** [comment]
Should be done on main!

**Comment by Tinche** [comment]
Well, changing the root aiohttp response type to StreamResponse at least.
